$(function(){
	//alert("working");
	$('#donate').click(function(){
		$('#cc-info').stop().animate({
			right:"0"
		},400);
		$('#parent')
	});
	$('#back').click(function(){
		$('#cc-info').stop().animate({
			right:"-1680px"
		},400);
	});
});